### ISSUE TITLE
Problems with CMake

### ISSUE THREAD

**Issue by FrizzyDoggenpop52** [loblao/libpandadna#70] opened 2020-08-18 10:26 UTC
CMake Error at CMakeLists.txt:176 (add_library):
  Cannot find source file:

    src/base_igate.cxx

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at CMakeLists.txt:176 (add_library):
  No SOURCES given to target: libpandadna

I am getting this error when I attempt to build.

**Comment by pythonengineer** [comment] 2020-08-18 19:45
This usually means that Interrogate did not run. Can you please provide the full log of you running CMake?

**Comment by FrizzyDoggenpop52** [comment] 2020-08-18 22:05
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
The system cannot find the path specified.

Interrogating base

The following command return a non-zero value (1): C:\Panda3D-1.11.0\bin\interrogate -D__inline -DCPPPARSER -DP3_INTERROGATE=1 -D__cplusplus -fnames -string -refcount -assert -S"C:\Panda3D-1.11.0/include/parser-inc" -S"C:\Panda3D-1.11.0/include" -I"C:\Panda3D-1.11.0/include" -I"C:\Users\grant\Desktop\toontown\libpandadna\src/base" -I"C:\Users\grant\Desktop\toontown\libpandadna\src/suit" -I"C:\Users\grant\Desktop\toontown\libpandadna\src/components" -srcdir "C:\Users\grant\Desktop\toontown\libpandadna\src/base" -oc "C:\Users\grant\Desktop\toontown\libpandadna\src/base_igate.cxx" -od "C:\Users\grant\Desktop\toontown\libpandadna\src/base.in" -python-native -DCPPPARSER -D__STDC__=1 -D__cplusplus -D__inline -D_X86_ -DWIN32_VC -DWIN32 -module libpandadna -library base -Dvolatile= config_dna.h dnabase.h DNALoader.h DNAStorage.h

libp3interrogatedb found
libp3pandatoolbase found
Configuring done
CMake Error at CMakeLists.txt:176 (add_library):
  Cannot find source file:

    src/base_igate.cxx

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

**Comment by FrizzyDoggenpop52** [comment] 2020-08-18 22:07
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
The system cannot find the path specified.

Interrogating base

The following command return a non-zero value (1): C:\Panda3D-1.11.0\bin\interrogate -D__inline -DCPPPARSER -DP3_INTERROGATE=1 -D__cplusplus -fnames -string -refcount -assert -S"C:\Panda3D-1.11.0/include/parser-inc" -S"C:\Panda3D-1.11.0/include" -I"C:\Panda3D-1.11.0/include" -I"C:\Users\john\Desktop\toontown\libpandadna\src/base" -I"C:\Users\john\Desktop\toontown\libpandadna\src/suit" -I"C:\Users\john\Desktop\toontown\libpandadna\src/components" -srcdir "C:\Users\john\Desktop\toontown\libpandadna\src/base" -oc "C:\Users\john\Desktop\toontown\libpandadna\src/base_igate.cxx" -od "C:\Users\john\Desktop\toontown\libpandadna\src/base.in" -python-native -DCPPPARSER -D__STDC__=1 -D__cplusplus -D__inline -D_X86_ -DWIN32_VC -DWIN32 -module libpandadna -library base -Dvolatile= config_dna.h dnabase.h DNALoader.h DNAStorage.h

libp3interrogatedb found
libp3pandatoolbase found
Configuring done
CMake Error at CMakeLists.txt:176 (add_library):
  Cannot find source file:

    src/base_igate.cxx

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

**Comment by pythonengineer** [comment] 2020-08-18 23:00
Judging by the "The system cannot find the path specified," your Panda3D installation is missing the interrogate binary. Make sure that your Panda3D has the `interrogate.exe` utility.

**Comment by FrizzyDoggenpop52** [comment] 2020-08-18 23:24
Just checked and interrogate.exe is present in the bin folder.

**Comment by pythonengineer** [comment] 2020-08-18 23:51
In that case, Interrogate will show the reason why it fails (for example, if it detects a syntax issue in the code it will show that), but the output you pasted does not show that. I'm wondering why there is a path error above "Interrogating base", and so I suggest checking all of the paths that CMake is using to make sure that they are valid, as that is likely relevant to your problem.

**Comment by FrizzyDoggenpop52** [comment] 2020-08-19 00:07
after tinkering with it I was able to fix the problem. Now when I build the project in visual studio I get this 
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1112	module machine type 'x64' conflicts with target machine type 'x86'	libpandadna	C:\Users\john\Desktop\libpanda.lib(libpanda.dll)	1

**Comment by pythonengineer** [comment] 2020-08-19 00:24
Inside of Visual Studio, you can create a new Win64 build mode copied off of the Win32 one. This will allow you to build it (you might have to add WIN64 and _M_X64 flags to your CMake as well) by changing the target machine type. I'm going to close this issue since this was not a bug but a support problem.

**Closed by pythonengineer** 2020-08-19 00:24 UTC
