### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by nate97** [loblao/libpandadna#64] opened 2019-04-07 03:11 UTC
*Synopsis: Ported fork of this tool over to Python3, unsure if it works, have no real way to test produced file*

Not sure if this is the best place to post this, but I've been wanting to port this tool over to Python3, so I've forked it, ran it through the 2to3 tool, and made some minor tweaks. It appears that it works successfully, however, I have no way as of yet to actually... test to see if the pdna files produced actually *work*.
I guess what I'm asking is, would anyone be-able to point me in the right direction for testing to see if this really works? I know, probably not the best place to ask this and maybe a bit too vague, but this is about the only place I found, thanks.

**Comment by pythonengineer** [comment] 2020-05-17 01:31
You should run the tests in the repository under the `test` directory with your pdna files to see if they work as intended, although I'm not sure how thorough the tests are. If all goes well, you should post a pull request to provide Python 3 support (ideally to the active development `feature/cxx-parser` branch, since master is out of date on many bugfixes).

**Comment by pythonengineer** [comment] 2020-05-21 05:32
Closing: 8fd05a7898a91f2254a51af7569f3a70fb4f82b3

**Closed by pythonengineer** 2020-05-21 05:32 UTC
Labels: question
